version: '3.8'

services:
  # --- Banco de Dados Relacional (Usuários) ---
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"

  # --- Banco de Dados NoSQL (Mensagens) ---
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  # --- Message Broker (Para comunicação distribuída) ---
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # --- Microsserviço de Autenticação  ---
  auth_service:
    build: ./auth_service
    ports:
      - "8001:8000"
    restart: always
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres/auth_db
    depends_on:
      - postgres

  # --- Microsserviço de Chat
  chat_service:
    build: ./chat_service
    ports:
      - "8002:8000" 
    restart: always
    environment:
      REDIS_URL: redis://redis:6379
      MONGO_URL: mongodb://mongo:27017
    depends_on:
      - redis
      - mongo
  
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html